[providers]
python = "3.11"

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"

[phases.build]
cmds = [
    "pip install -r requirements.txt"
]

[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "postgresql"
] 