[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"

[[deploy.healthcheck]]
path = "/health"
timeout = 60
interval = 60 