"""Initial migration

Revision ID: 3ca0e38a88ec
Revises: 
Create Date: 2025-06-26 19:51:44.650014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca0e38a88ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('enable_notifications', sa.Boolean(), nullable=True),
    sa.Column('notification_language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('calendar_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_start_time', sa.String(length=10), nullable=True),
    sa.Column('work_end_time', sa.String(length=10), nullable=True),
    sa.Column('work_days', sa.Integer(), nullable=True),
    sa.Column('default_reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('enable_email_notifications', sa.Boolean(), nullable=True),
    sa.Column('enable_telegram_notifications', sa.Boolean(), nullable=True),
    sa.Column('enable_sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('google_calendar_enabled', sa.Boolean(), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('outlook_calendar_enabled', sa.Boolean(), nullable=True),
    sa.Column('outlook_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('auto_schedule_enabled', sa.Boolean(), nullable=True),
    sa.Column('min_meeting_duration', sa.Integer(), nullable=True),
    sa.Column('max_meeting_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_calendar_settings_id'), 'calendar_settings', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_settings_uuid'), 'calendar_settings', ['uuid'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('preferred_areas', sa.JSON(), nullable=False),
    sa.Column('budget_min', sa.BigInteger(), nullable=True),
    sa.Column('budget_max', sa.BigInteger(), nullable=True),
    sa.Column('property_types', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('client_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    op.create_table('event_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('title_template', sa.String(length=255), nullable=False),
    sa.Column('description_template', sa.Text(), nullable=True),
    sa.Column('default_duration', sa.Integer(), nullable=True),
    sa.Column('default_location', sa.String(length=500), nullable=True),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_templates_id'), 'event_templates', ['id'], unique=False)
    op.create_index(op.f('ix_event_templates_uuid'), 'event_templates', ['uuid'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Enum('APARTMENT', 'HOUSE', 'COMMERCIAL', 'LAND', 'GARAGE', 'OTHER', name='propertytype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'RENTED', 'INACTIVE', name='propertystatus'), nullable=False),
    sa.Column('deal_type', sa.Enum('SALE', 'RENT', 'BOTH', name='dealtype'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('living_area', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('price_sale', sa.BigInteger(), nullable=True),
    sa.Column('price_rent', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=10), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('property_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_address'), 'properties', ['address'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_deal_type'), 'properties', ['deal_type'], unique=False)
    op.create_index(op.f('ix_properties_district'), 'properties', ['district'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_index(op.f('ix_properties_user_id'), 'properties', ['user_id'], unique=False)
    op.create_index(op.f('ix_properties_uuid'), 'properties', ['uuid'], unique=True)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('external_calendar_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_end_time'), 'calendar_events', ['end_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_time'), 'calendar_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_status'), 'calendar_events', ['status'], unique=False)
    op.create_index(op.f('ix_calendar_events_uuid'), 'calendar_events', ['uuid'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('event_type', sa.Enum('SHOWING', 'MEETING', 'DEAL', 'TASK', 'CALL', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'POSTPONED', name='eventstatus'), nullable=False),
    sa.Column('reminders', sa.JSON(), nullable=False),
    sa.Column('created_from', sa.Enum('VOICE', 'TEXT', 'IMAGE', 'MANUAL', 'API', name='createdfrom'), nullable=False),
    sa.Column('original_message', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('property_id', sa.BigInteger(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_client_id'), 'events', ['client_id'], unique=False)
    op.create_index(op.f('ix_events_created_from'), 'events', ['created_from'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_property_id'), 'events', ['property_id'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('ai_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('property_id', sa.BigInteger(), nullable=True),
    sa.Column('processing_type', sa.Enum('SPEECH_TO_TEXT', 'TEXT_ANALYSIS', 'IMAGE_OCR', 'INTENT_CLASSIFICATION', 'ENTITY_EXTRACTION', 'ROUTE_OPTIMIZATION', name='aiprocessingtype'), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'YANDEX', 'LOCAL', 'EASYOCR', 'WHISPER', name='aiprovider'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ai_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_data_client_id'), 'ai_data', ['client_id'], unique=False)
    op.create_index(op.f('ix_ai_data_created_at'), 'ai_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_data_event_id'), 'ai_data', ['event_id'], unique=False)
    op.create_index(op.f('ix_ai_data_processing_type'), 'ai_data', ['processing_type'], unique=False)
    op.create_index(op.f('ix_ai_data_property_id'), 'ai_data', ['property_id'], unique=False)
    op.create_index(op.f('ix_ai_data_provider'), 'ai_data', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_data_user_id'), 'ai_data', ['user_id'], unique=False)
    op.create_table('event_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('reminder_time', sa.DateTime(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_reminders_id'), 'event_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_event_reminders_reminder_time'), 'event_reminders', ['reminder_time'], unique=False)
    op.create_index(op.f('ix_event_reminders_uuid'), 'event_reminders', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_reminders_uuid'), table_name='event_reminders')
    op.drop_index(op.f('ix_event_reminders_reminder_time'), table_name='event_reminders')
    op.drop_index(op.f('ix_event_reminders_id'), table_name='event_reminders')
    op.drop_table('event_reminders')
    op.drop_index(op.f('ix_ai_data_user_id'), table_name='ai_data')
    op.drop_index(op.f('ix_ai_data_provider'), table_name='ai_data')
    op.drop_index(op.f('ix_ai_data_property_id'), table_name='ai_data')
    op.drop_index(op.f('ix_ai_data_processing_type'), table_name='ai_data')
    op.drop_index(op.f('ix_ai_data_event_id'), table_name='ai_data')
    op.drop_index(op.f('ix_ai_data_created_at'), table_name='ai_data')
    op.drop_index(op.f('ix_ai_data_client_id'), table_name='ai_data')
    op.drop_table('ai_data')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_property_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_created_from'), table_name='events')
    op.drop_index(op.f('ix_events_client_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_calendar_events_uuid'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_status'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_time'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_end_time'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_properties_uuid'), table_name='properties')
    op.drop_index(op.f('ix_properties_user_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_district'), table_name='properties')
    op.drop_index(op.f('ix_properties_deal_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_address'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_event_templates_uuid'), table_name='event_templates')
    op.drop_index(op.f('ix_event_templates_id'), table_name='event_templates')
    op.drop_table('event_templates')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_calendar_settings_uuid'), table_name='calendar_settings')
    op.drop_index(op.f('ix_calendar_settings_id'), table_name='calendar_settings')
    op.drop_table('calendar_settings')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ### 